export const POOL_SIZES = {
  ANIMATIONS: 2000,
  SPRITES: 3000
} as const;

export const ANIMATION_CONFIG = {
  ROOF_FADE_DURATION: 500,
  ALPHA_VISIBLE: 1.0,
  ALPHA_HIDDEN: 0.0
} as const;

export const COLLISION_CONFIG = {
  TRIGGER_TOLERANCE: 0.2,
  BOX_POLYGON_TOLERANCE: 0.1
} as const;
