/** obj.dat field name → attributes.name (from 2020-11-09_full.sql) */
export const FIELD_TO_ATTRIBUTE = {
  Agarrable: "agarrable",
  Abierta: "abierta",
  MinHAM: "minham",
  MinHam: "minham",
  Valor: "valor",
  Crucial: "crucial",
  Anim: "anim",
  RazaEnanaAnim: "razaenanaanim",
  MinHit: "minhit",
  MaxHit: "maxhit",
  LingH: "lingh",
  LingP: "lingp",
  LingO: "lingo",
  SkHerreria: "skherreria",
  abierta: "abierta",
  Llave: "llave",
  IndexAbierta: "indexabierta",
  IndexCerrada: "indexcerrada",
  IndexCerradaLlave: "indexcerradallave",
  CantItems: "cantitems",
  NroItems: "nroitems",
  VGrande: "vgrande",
  Vgrande: "vgrande",
  Texto: "texto",
  Clave: "clave",
  Apuñala: "apuñala",
  Upgrade: "upgrade",
  NumRopaje: "numropaje",
  MaxDef: "maxdef",
  MinDef: "mindef",
  TipoPocion: "tipopocion",
  MaxModificador: "maxmodificador",
  MinModificador: "minmodificador",
  DuracionEfecto: "duracionefecto",
  MinAgu: "minagu",
  MinST: "minst",
  Respawn: "respawn",
  MinHP: "minhp",
  Real: "real",
  Madera: "madera",
  SkCarpinteria: "skcarpinteria",
  Mujer: "mujer",
  MineralIndex: "mineralindex",
  LingoteIndex: "lingoteindex",
  Lingoteindex: "lingoteindex",
  MinSkill: "minskill",
  HechizoIndex: "hechizoindex",
  StaffPower: "staffpower",
  RazaEnana: "razaenana",
  Razaenana: "razaenana",
  Snd1: "snd1",
  SND1: "snd1",
  Snd2: "snd2",
  SND2: "snd2",
  Snd3: "snd3",
  SND3: "snd3",
  Caos: "caos",
  Radio: "radio",
  DefensaMagicaMin: "defensamagicamin",
  DefensaMagicaMax: "defensamagicamax",
  StaffDamageBonus: "staffdamagebonus",
  Newbie: "newbie",
  newbie: "newbie",
  MaderaElfica: "maderaelfica",
  Proyectil: "proyectil",
  Municiones: "municiones",
  NoSeCae: "nosecae",
  Nosecae: "nosecae",
  Envenena: "envenena",
  Refuerzo: "refuerzo",
  MochilaType: "mochilatype",
  Guante: "guante",
  Hombre: "hombre",
  RazaDrow: "razadrow",
  Acuchilla: "acuchilla",
};

/** attributes.name → id (stable reference data from 2020-11-09_full.sql) */
export const ATTRIBUTE_IDS = {
  agarrable: 1,
  minham: 2,
  valor: 3,
  crucial: 4,
  anim: 5,
  razaenanaanim: 6,
  minhit: 7,
  maxhit: 8,
  lingh: 9,
  lingp: 10,
  lingo: 11,
  skherreria: 12,
  abierta: 13,
  llave: 14,
  indexabierta: 15,
  indexcerrada: 16,
  indexcerradallave: 17,
  cantitems: 18,
  nroitems: 19,
  vgrande: 20,
  texto: 21,
  clave: 22,
  apuñala: 23,
  upgrade: 24,
  numropaje: 25,
  maxdef: 26,
  mindef: 27,
  tipopocion: 29,
  maxmodificador: 30,
  minmodificador: 31,
  duracionefecto: 32,
  minagu: 33,
  minst: 34,
  respawn: 35,
  minhp: 36,
  real: 37,
  madera: 38,
  skcarpinteria: 39,
  mujer: 40,
  mineralindex: 41,
  lingoteindex: 42,
  minskill: 43,
  hechizoindex: 44,
  staffpower: 45,
  razaenana: 46,
  snd1: 47,
  snd2: 48,
  snd3: 49,
  caos: 50,
  radio: 51,
  defensamagicamin: 52,
  defensamagicamax: 53,
  staffdamagebonus: 54,
  newbie: 55,
  maderaelfica: 56,
  proyectil: 57,
  municiones: 58,
  nosecae: 59,
  envenena: 60,
  refuerzo: 61,
  mochilatype: 62,
  guante: 63,
  hombre: 64,
  razadrow: 65,
  acuchilla: 66,
};

export const BASE_OBJECT_FIELDS = new Set([
  "Name",
  "ObjType",
  "GrhIndex",
  "Desc",
  "Description",
  "ID",
]);

export const CLASS_PROHIBITION_PREFIX = "CP";
