import { describe, expect, it } from "vitest";

import { parseSeedStatements, splitSqlStatements } from "./sqlStatements.js";

const npcInsert =
  "INSERT INTO `npcs` (`id`, `description`) VALUES (34, 'Hola;\ncomerciante') ON DUPLICATE KEY UPDATE `description`=VALUES(`description`)";
const shopInsert =
  "INSERT INTO `npc_shop_items` (`npcId`, `slot`, `objectId`, `amount`) VALUES (34, 1, 100, 1) ON DUPLICATE KEY UPDATE `objectId`=VALUES(`objectId`)";

const sql = `-- Generated by bao seed
-- 2026-06-12T00:00:00.000Z

-- @bao-npc:34
${npcInsert};
${shopInsert};
`;

function normalizeForTest(seedSql: string) {
  return seedSql
    .replace(/^-- Generated by bao seed\r?\n-- [^\n]+\r?\n+/u, "")
    .replace(/^(-- @bao-npc:\d+)\r?\n/gm, ";\n$1;\n");
}

describe("splitSqlStatements", () => {
  it("splits on semicolons outside strings", () => {
    const statements = splitSqlStatements(normalizeForTest(sql));
    expect(statements.length).toBe(3);
  });
});

describe("parseSeedStatements", () => {
  it("groups statements by npc marker", () => {
    const parsed = parseSeedStatements(sql);
    expect(parsed.length).toBe(2);
    expect(parsed[0].npcId).toBe(34);
    expect(parsed[1].npcId).toBe(34);
    expect(parsed[0].npcBlockEnd).toBe(false);
    expect(parsed[1].npcBlockEnd).toBe(true);
  });
});
